/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CompetitionsIndexImport } from './routes/competitions/index'
import { Route as CompetitionsCompetitionIdImport } from './routes/competitions/$competitionId'
import { Route as TeamsTeamIdCompetitionIdImport } from './routes/teams/$teamId/$competitionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIndexRoute = CompetitionsIndexImport.update({
  path: '/competitions/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsCompetitionIdRoute = CompetitionsCompetitionIdImport.update({
  path: '/competitions/$competitionId',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamIdCompetitionIdRoute = TeamsTeamIdCompetitionIdImport.update({
  path: '/teams/$teamId/$competitionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/competitions/$competitionId': {
      id: '/competitions/$competitionId'
      path: '/competitions/$competitionId'
      fullPath: '/competitions/$competitionId'
      preLoaderRoute: typeof CompetitionsCompetitionIdImport
      parentRoute: typeof rootRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamId/$competitionId': {
      id: '/teams/$teamId/$competitionId'
      path: '/teams/$teamId/$competitionId'
      fullPath: '/teams/$teamId/$competitionId'
      preLoaderRoute: typeof TeamsTeamIdCompetitionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/teams/$teamId/$competitionId': typeof TeamsTeamIdCompetitionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/teams/$teamId/$competitionId': typeof TeamsTeamIdCompetitionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/teams/$teamId/$competitionId': typeof TeamsTeamIdCompetitionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions/$competitionId'
    | '/competitions'
    | '/teams/$teamId/$competitionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions/$competitionId'
    | '/competitions'
    | '/teams/$teamId/$competitionId'
  id:
    | '__root__'
    | '/'
    | '/competitions/$competitionId'
    | '/competitions/'
    | '/teams/$teamId/$competitionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsCompetitionIdRoute: typeof CompetitionsCompetitionIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  TeamsTeamIdCompetitionIdRoute: typeof TeamsTeamIdCompetitionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsCompetitionIdRoute: CompetitionsCompetitionIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  TeamsTeamIdCompetitionIdRoute: TeamsTeamIdCompetitionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/competitions/$competitionId",
        "/competitions/",
        "/teams/$teamId/$competitionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/competitions/$competitionId": {
      "filePath": "competitions/$competitionId.tsx"
    },
    "/competitions/": {
      "filePath": "competitions/index.tsx"
    },
    "/teams/$teamId/$competitionId": {
      "filePath": "teams/$teamId/$competitionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
